"""
research.types — Web Research domain models and type definitions (V6)
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


class ResearchDepth(str, enum.Enum):
    """
    Controls the intensity and page-fetching depth of web research.
    """
    QUICK = "quick"   # Snippet-only, fast, low latency (3-5 results)
    DEEP = "deep"     # Fetches full source web pages and extracts rich evidence (5-8 results)


@dataclass
class WebSource:
    """
    Tracked web source with provenance metadata.
    """
    url: str
    title: str
    snippet: str
    domain: str = ""
    published_date: str | None = None
    retrieved_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    source_type: str = "web_search"
    content_hash: str = ""
    raw_content: str | None = None
    score: float = 0.0


@dataclass
class WebResult:
    """
    Normalized result from DuckDuckGo search provider.
    """
    url: str
    title: str
    snippet: str
    score: float = 0.0
    source: str = "duckduckgo"
    domain: str = ""
    raw_content: str | None = None


@dataclass
class EvidenceItem:
    """
    Extracted, source-grounded evidence passage with provenance.
    """
    source_url: str
    source_title: str
    content: str
    relevance_score: float
    retrieved_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    domain: str = ""


@dataclass
class ResearchPlan:
    """
    Plan generated by ResearchPlanner prior to executing searches.
    """
    query: str
    sub_queries: list[str] = field(default_factory=list)
    depth: ResearchDepth = ResearchDepth.QUICK
    max_results: int = 5
    fetch_pages: bool = False


@dataclass
class ResearchContext:
    """
    Bounded, source-grounded research context package for the Agent Core.
    """
    query: str
    summary_text: str
    evidence_items: list[EvidenceItem] = field(default_factory=list)
    sources: list[WebSource] = field(default_factory=list)
    token_count: int = 0
    provider_used: str = "duckduckgo"


@dataclass
class ResearchResponse:
    """
    Standardized response returned by ResearchRouter and WebResearchEngine.
    """
    query: str
    results: list[WebResult]
    provider_used: str = "duckduckgo"
    total_results: int = 0
    evidence_items: list[EvidenceItem] = field(default_factory=list)
    context_text: str = ""
