// Kora Desktop — WebSocket message types (mirrors shared/protocol/schema.json)
// This file is the single source of truth for message types in Dart.

enum WsMessageType {
  chatRequest,
  chatChunk,
  chatDone,
  chatCancel,
  chatCancelled,
  planCreated,
  planUpdate,
  toolStart,
  toolCallNotify,
  toolResult,
  toolResultNotify,
  toolError,
  permissionRequest,
  permissionResponse,
  indexRequest,
  indexProgress,
  indexDone,
  indexError,
  heartbeat,
  providerStatus,
  automationStarted,
  automationPlan,
  automationStepStart,
  automationStepFinish,
  automationCompleted,
  automationFailed,
  systemMetrics,
  error;

  static WsMessageType fromString(String s) {
    return switch (s.toUpperCase().trim()) {
      'CHAT_REQUEST'        => chatRequest,
      'CHAT_CHUNK'          => chatChunk,
      'CHAT_DONE'           => chatDone,
      'CHAT_CANCEL'         => chatCancel,
      'CANCEL_REQUEST'      => chatCancel,
      'CHAT_CANCELLED'      => chatCancelled,
      'PLAN_CREATED'        => planCreated,
      'PLAN_UPDATE'         => planUpdate,
      'TOOL_START'          => toolStart,
      'TOOL_CALL_NOTIFY'    => toolCallNotify,
      'TOOL_RESULT'         => toolResult,
      'TOOL_RESULT_NOTIFY'  => toolResultNotify,
      'TOOL_ERROR'          => toolError,
      'PERMISSION_REQUEST'  => permissionRequest,
      'PERMISSION_RESPONSE' => permissionResponse,
      'INDEX_REQUEST'       => indexRequest,
      'INDEX_PROGRESS'      => indexProgress,
      'INDEX_DONE'          => indexDone,
      'INDEX_ERROR'         => indexError,
      'HEARTBEAT'           => heartbeat,
      'PROVIDER_STATUS'     => providerStatus,
      'AUTOMATION_STARTED'     => automationStarted,
      'AUTOMATION_PLAN'        => automationPlan,
      'AUTOMATION_STEP_START'  => automationStepStart,
      'AUTOMATION_STEP_FINISH' => automationStepFinish,
      'AUTOMATION_COMPLETED'   => automationCompleted,
      'AUTOMATION_FAILED'      => automationFailed,
      'SYSTEM_METRICS'         => systemMetrics,
      'ERROR'               => error,
      _                     => error,
    };
  }

  String toApiString() {
    return switch (this) {
      WsMessageType.chatRequest        => 'CHAT_REQUEST',
      WsMessageType.chatChunk          => 'CHAT_CHUNK',
      WsMessageType.chatDone           => 'CHAT_DONE',
      WsMessageType.chatCancel         => 'CHAT_CANCEL',
      WsMessageType.chatCancelled      => 'CHAT_CANCELLED',
      WsMessageType.planCreated        => 'PLAN_CREATED',
      WsMessageType.planUpdate         => 'PLAN_UPDATE',
      WsMessageType.toolStart          => 'TOOL_START',
      WsMessageType.toolCallNotify     => 'TOOL_CALL_NOTIFY',
      WsMessageType.toolResult         => 'TOOL_RESULT',
      WsMessageType.toolResultNotify   => 'TOOL_RESULT_NOTIFY',
      WsMessageType.toolError          => 'TOOL_ERROR',
      WsMessageType.permissionRequest  => 'PERMISSION_REQUEST',
      WsMessageType.permissionResponse => 'PERMISSION_RESPONSE',
      WsMessageType.indexRequest       => 'INDEX_REQUEST',
      WsMessageType.indexProgress      => 'INDEX_PROGRESS',
      WsMessageType.indexDone          => 'INDEX_DONE',
      WsMessageType.indexError         => 'INDEX_ERROR',
      WsMessageType.heartbeat          => 'HEARTBEAT',
      WsMessageType.providerStatus     => 'PROVIDER_STATUS',
      WsMessageType.automationStarted  => 'AUTOMATION_STARTED',
      WsMessageType.automationPlan     => 'AUTOMATION_PLAN',
      WsMessageType.automationStepStart  => 'AUTOMATION_STEP_START',
      WsMessageType.automationStepFinish => 'AUTOMATION_STEP_FINISH',
      WsMessageType.automationCompleted  => 'AUTOMATION_COMPLETED',
      WsMessageType.automationFailed     => 'AUTOMATION_FAILED',
      WsMessageType.systemMetrics      => 'SYSTEM_METRICS',
      WsMessageType.error              => 'ERROR',
    };
  }
}
